name: Core plugin

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: ./gradlew shadowJar
        env:
          USERNAME: ${{ secrets.GPR_ACTOR }}
          TOKEN: ${{ secrets.GPR_TOKEN }}

      - name: Publish to GitHub Packages
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: ./gradlew api:publish core:publish
        env:
          USERNAME: ${{ secrets.GPR_ACTOR }}
          TOKEN: ${{ secrets.GPR_TOKEN }}